### PR TITLE
Utilize Kernel#warn

### PR DESCRIPTION
**Pull request by drewbug**

### CODE REVIEW

**Comment by drewbug** [comment]
This will let me kill this hack:

    STDERR.define_singleton_method(:puts) { |*| }
    silence_warnings { require 'opencl_ruby_ffi' }
    STDERR.singleton_class.send :undef_method, :puts

**Comment by drewbug** [comment]
This will let me put this ugly hack to rest:

    def STDERR.puts(*); end
    silence_warnings { require 'opencl_ruby_ffi' }
    STDERR.singleton_class.send :remove_method, :puts

**Comment by Kerilk** [comment]
Thanks for the contribution, merging. I will release the gem on Monday.

**Comment by drewbug** [comment]
Thanks!

**Comment by Kerilk** [comment]
Done

**Pull request merged**
